version: '3'
services:
  hotel-api:
    build: .
    ports: 
      - "127.0.0.1:8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://es:9200

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9500:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:5609:5601"

networks:
  elastic:

volumes:
  data:
